CREATE CATALOG IF NOT EXISTS ingest;
CREATE SCHEMA IF NOT EXISTS ingest.default;
CREATE CATALOG IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS bronze.default;
CREATE CATALOG IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS silver.default;
CREATE CATALOG IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS gold.default;